# Combine JSON files and remove all dups
nodups:
    command: "cat data/direct_tweets.json data/stream.json | ./rmdups.py > data/nodups.json"
    delOnFail: true
    direct: true
    inputs:
        - common.py
        - rmdups.py
        - data/direct_tweets.json
        - data/stream.json
    outputs:
        - data/nodups.json

# Split de-dup'ed tweets into pre, during, and post game
split:
    command: "./timesplit.py data/split < data/nodups.json"
    delOnFail: true
    direct: true
    inputs:
        - common.py
        - timesplit.py
        - data/nodups.json
    outputs:
        - data/split-pregame.json
        - data/split-game.json
        - data/split-postgame.json

# Convert pre game JSON to CSV
pre-csv:
    command: "./makecsv.py < data/split-pregame.json > data/split-pregame.csv"
    delOnFail: true
    direct: false
    inputs:
        - common.py
        - makecsv.py
        - data/split-pregame.json
    outputs:
        - data/split-pregame.csv

# Convert during game JSON to CSV
dur-csv:
    command: "./makecsv.py < data/split-game.json > data/split-game.csv"
    delOnFail: true
    direct: false
    inputs:
        - common.py
        - makecsv.py
        - data/split-game.json
    outputs:
        - data/split-game.csv

# Convert post game JSON to CSV
post-csv:
    command: "./makecsv.py < data/split-postgame.json > data/split-postgame.csv"
    delOnFail: true
    direct: false
    inputs:
        - common.py
        - makecsv.py
        - data/split-postgame.json
    outputs:
        - data/split-postgame.csv

# ZIP up CSV for delivery
deliver:
    command: "zip -v -j data/superbowl-twitter.zip data/hashtags.txt data/*.csv"
    delOnFail: true
    direct: true
    inputs:
        - data/hashtags.txt
        - data/split-pregame.csv
        - data/split-game.csv
        - data/split-postgame.csv
    outputs:
        - data/superbowl-twitter.zip
